### PR TITLE
upgrade core-js to the latest version

### PR DESCRIPTION
**Pull request by milewski**
Hi this upgrade the corejs dependency to version 3, previous it was on v2

### CODE REVIEW

**Comment by milewski** [comment]
Ping @idiotWu

**Comment by idiotWu** [comment]
Sorry for the delay. Can you update the branch so that it can be merged into dev?

**Comment by milewski** [comment]
Resolved the conflicts

**Comment by idiotWu** [comment]
Shipped as v8.6.0. Thanks!

**Comment by wintercounter** [comment]
Hi all, sorry for commenting on a closed PR but this is not a solution. I do not want to load polyfills. A library should never include such, and let the user decide how they want to polyfill.

**Comment by idiotWu** [comment]
@wintercounter I agree with that and I'm going to remove all polyfills in v9 (if I have time). However, as for v8, I think we should still keep the polyfills for consistency.

**Comment by wintercounter** [comment]
Thank you for the quick response.

**Comment by jpike88** [comment]
@idiotWu I just noticed this... 4 years ago. I'm going to make a PR that removes core-js for you

**Pull request merged**
