### PR TITLE
simplify code contributions by automating the dev setup.

### PR DESCRIPTION
**Pull request by nisarhassan12**
## Description

Hi. I work for Gitpod(an online IDE which is free for Open Source) and we are currently on a mission to simplify contributors onboarding experience for cool and popular Open Source projects.

This Pr adds Gitpod config to the repo via which, anyone would be able to launch a workspace where it will automatically:

- clone the `smooth-scrollbar` repo.
- install the dependencies i.e via `npm start`.
- run `npm start` to start the web server.

All of this can be helpful for newcomers/beginners i.e the can start in just a single click without having to set anything up.

You can give it a try on my fork of the repo via the following link:

https://gitpod.io/#https://github.com/nisarhassan12/smooth-scrollbar

This is how it looks:

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by idiotWu** [comment]
VERY impressive! Thanks! 

(not sure why the CI is still hanging 😕 )

**Comment by nisarhassan12** [comment]
Sorry pushed some recent changes just a few mins ago.

**Comment by idiotWu** [comment]
@nisarhassan12 yeah I saw those new commits and the build was already finished on Travis CI, but GitHub was still waiting for status reports 🤔. You can see the same problem occurred in other PRs:

image

**Comment by nisarhassan12** [comment]
Yeah. Looks like an issue with Github CI.

**Pull request merged**
