### PR TITLE
Added invertDelta option ✨ 

### PR DESCRIPTION
**Pull request by liqueflies**
How about this kind of solution?
It can be used temporarily until v8.
Also because we have to fork `react-smooth-scrollbar` only for the dependency and it's really annoying.

## Description
Added `invertDelta` option on smooth-scrollbar to invert the scroll delta, is really simple. In the future it could be changed with `reducers` concept.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by idiotWu** [comment]
Like I've explained in #43, I don't really want to add this option because it behaves strange on devices with trackpad (eg my MacBook). I just can't understand why so many people want this feature 😕

**Comment by liqueflies** [comment]
I've a MacBook but I also use normal mouse. I think a lot of people use normal input device as mouse and not trackpads so they can't perform horizontal scroll. For design concept sometimes you need to "normalize" your input devices behaviour, so if your website is moving only in the horizontal axis, you let people scroll vertical as usual performing the horizontal scroll.

http://workshop.ddd.it is another example, I can perform the scroll with every input device, and this is important because is based in horizontal axis.

 Is an option and +3 lines of code, and solves the problem :)

**Comment by idiotWu** [comment]
Yeah I see your point. Hmmm...give me three days to finish v8. If I can't, then you win and I will merge this PR :)

**Comment by liqueflies** [comment]
Yeah! Thank you 💪

**Comment by idiotWu** [comment]
Hey @liqueflies, I am having some problems refactoring overscroll effect. I'm afraid the first beta release won't come out today😅.

So I'm going to merge this PR first. Would you be so kind as to update the docs for `invertDelta` option too?

PS: I think the problems could be solved in one or two days, you can try out the beta release of v8 then!

**Comment by idiotWu** [comment]
Hey there! [8.0.0](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v8.0.0) is out! Any feedback would be greatly appreciated 🙌 .

**Comment by liqueflies** [comment]
Sorry I was away for weekend :(

Good job! Just one thing: upgrading react-smooth-scrollbar (so smooth-scrollbar also) the smooth-scrollbar.css isn't in dist directory. I know this isn't the right place, btw I can open an issue.

Thank you for your work :)

**Comment by idiotWu** [comment]
1. CSS is bundled in JS so there's no need to import it anymore.

2. Keep in mind that `plugin.transformDelta` will be invoked after almost all the event calls. It would be better to filter event type in your plugin like:

```js
transformDelta(delta, fromEvent) {
    if (!/wheel/.test(fromEvent.type)) return delta;

    return {
      x: delta.y,
      y: delta.x,
    };
  }
```

**Comment by idiotWu** [comment]
The example of `InvertDeltaPlugin` is added to docs. [Click Me](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/plugin.md#example-invert-delta)

I was too tired yesterday so I forgot to leave some tips for updating to v8 😅 . Again, sorry for the inconvenience 🙇 .

You can check [migration guide](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/migration.md) for more details.

**Comment by HectorLS** [comment]
Hello
Can you helping me achieving this ? 
My smooth-scrollbar works sweet. But in one page i need to enable the horizontal scroll
for the mouse wheel.

```javascript
// code added from the in the Wiki
import Scrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';

class InvertDeltaPlugin extends ScrollbarPlugin {
  static pluginName = 'invertDelta';

  static defaultOptions = {
    events: [],
  };

  transformDelta(delta, fromEvent) {
    if (this.shouldInvertDelta(fromEvent)) {
      return {
        x: delta.y,
        y: delta.x,
      };
    }

    return delta;
  }

  shouldInvertDelta(fromEvent) {
    return this.options.events.some(rule => fromEvent.type.match(rule));
  }
}

Scrollbar.use(InvertDeltaPlugin);
```


my setup
```javascript

class Scroller {
  constructor() {
    this.options = {
      damping: 0.25,
      thumbMinSize: 5,
      renderByPixel: true,
      alwaysShowTracks: false,
      continuousScrolling: true,
      plugins: {
        invertDelta: {
          events: [/wheel/],
        },
      }
    };

    this.init();
  }

  init(container = document) {
    this.element = container.getElementsByClassName('scrollbar-wrapper')[0];

    if (!!this.element) {
      this.scrollbar = Scrollbar.init(this.element, this.options);
    } 
  }
```

As soon as i add the plugin, the scroll stop working, but no error at all.
Any help would be much appreciated  @idiotWu  @liqueflies   🙏 

Thanks in advance

**Comment by HectorLS** [comment]
"smooth-scrollbar": "^8.2.5"

Hello, i got this plugin running and working 🎉  but seems to set a wrong scrollTop, ( in this case wrong scrollLeft )

Scroll rightfully until the end of the web, but at the beginning seems to miss some pixels 🤔 ( like 200 or more depending of the viewport width )

```javascript
import Scrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';  

// Wiki plugin ! 👏 
class InvertDeltaPlugin extends ScrollbarPlugin {
  static pluginName = 'invertDelta';

  static defaultOptions = {
    events: [],
  };

  transformDelta(delta, fromEvent) {
    if (this.shouldInvertDelta(fromEvent)) {
      return {
        x: delta.y,
        y: delta.x,
      };
    }

    return delta;
  }

  shouldInvertDelta(fromEvent) {
    return this.options.events.some(rule => fromEvent.type.match(rule));
  }
}

Scrollbar.use(InvertDeltaPlugin);

// Constructor
class Scroller {
  constructor(mobileOrTablet) {
    this.options = {
      damping: 0.25,
      thumbMinSize: 5,
      renderByPixel: true,
      alwaysShowTracks: false,
      continuousScrolling: true
      plugins: {
        invertDelta: {
          events: [/wheel/]
        }
      }
    };
  }

  init(container = document) {
    this.element = container.getElementsByClassName('scrollbar-wrapper')[0];

    if (!!this.element) {
      this.scrollbar = Scrollbar.init(this.element, this.options);
    }
  }
}
```

Any help  would be much appreciated 🙏  @liqueflies  @idiotWu 

Thank in advance

**Comment by idiotWu** [comment]
@HectorLS has scrollbar already been initialized when you started scrolling?

**Comment by HectorLS** [comment]
@idiotWu no, initialize on content Load, but i'm adding new content after that.

**Comment by HectorLS** [comment]
Omg fixed!

So weird, i had a container with columns and:

```sass
.container {
  display: flex;
  flex-wrap:nowrap;
  justify-content: center
}
```

the `justify-content: center` was keeping the stuff centered, even if i added new columns ( so the left ones started to hide itself 🤦‍♂️ 

fixed with `justify-content: flex-start` to keep the web flow from left to right

**Pull request closed without merging**
